package nightlifebuddy;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.FetchOptions;
import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;
import com.google.appengine.api.datastore.Query;
import com.google.appengine.api.datastore.Transaction;
import com.google.appengine.api.datastore.Query.Filter;
import com.google.appengine.api.datastore.Query.FilterOperator;
import com.google.appengine.api.datastore.Query.FilterPredicate;

/**
 * GAE ENTITY UTIL CLASS: "Genre" <br>
 * PARENT: NONE <br>
 * KEY: A name long Id generated by GAE <br>
 * FEATURES: <br>
 * - "name" a {@link String} with the name of the genre (e.g. "Lima")<br>
 * AUTHORS: Jason Pierce <br>
 */

public class Genres 
{

	//
    // SECURITY
    //
    
    /**
     * Private constructor to avoid instantiation.
     */
	private Genres()
	{}

	//
	// LIST FOR THE RESULTS OF THE SEARCH DONE
	//

	/**
	 * The list for the results that will be used in the index page
	 */
	private static List<Entity> result = null;

	//
	// KIND
	//

	/**
	 * The name of the Genre ENTITY KIND used in GAE.
	 */
	private static final String ENTITY_KIND = "Genre";


	/**
     * Return the Key for a given genre name given as String. 
     * @param name A string with the genreName (a long).
     * @return the Key for this genreName. 
     */
	public static Key getKey(String name) 
	{
        Key genreKey = KeyFactory.createKey(ENTITY_KIND, name);
        return genreKey;
	}


	/**
     * Return the string ID corresponding to the key for the genre.
     * @param genre The GAE Entity storing the genre.
     * @return A string with the lot ID (a long).
     */
	public static String getStringID(Entity genre) 
	{
        return Long.toString(genre.getKey().getId());
	}

	//
    // NAME
    //
    
    /**
     * The property name for the <b>name</b> of the genre profile.
     */
	private static final String NAME_PROPERTY = "name";

	/**
     * Return the name of the genre. 
     * @param genre The GAE Entity storing the genre.
     * @return the name of the genre. 
     */
	public static String getName(Entity genre) 
	{
        Object name;
        if (genre == null) 
        	name = "No Genre Assigned";
        else
        	name = genre.getProperty(NAME_PROPERTY);
        return (String) name;
	}

	/**
     * The regular expression pattern for the name of the genre profile.
     */
    private static final Pattern NAME_PATTERN = Pattern.compile("\\A[A-Za-z]+([ -][A-Za-z]+){0,10}\\Z");
    
    
    /**
     * Check if the name is correct for a genre. 
     * @param name The checked string. 
     * @return true is the name is correct. 
     */
    public static boolean checkName(String name) {
        Matcher matcher=NAME_PATTERN.matcher(name);
        return matcher.find();
    }
    
    
    
	//
    // CREATE A GENRE
    //

    /**
     * Create a new genre if the genreName is correct and none exists with this name.
     * @param name The name for this genre.
     * @return the Entity created with this name or null if error
     */
	public static Entity createGenre(String name) 
	{
        Entity genre = null;
        DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
        Transaction txn = datastore.beginTransaction();
        try {
        
                genre = getGenreWithName(name);
                if (genre!=null) {
                        return null;
                }
                
                genre = new Entity(ENTITY_KIND);
                genre.setProperty(NAME_PROPERTY, name);
                datastore.put(genre);

            txn.commit();
        } finally {
            if (txn.isActive()) {
                txn.rollback();
            }
        }
        
        return genre;
	}


	/**
     * Get an genre based on a string containing its genreName.
     * @param name The name of the genre as a String.
     * @return A GAE {@link Entity} for the genre or <code>null</code> if none or error.
     */
	public static Entity getGenreWithName(String name) 
	{
		DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
        return getGenreWithName(datastore, name);
	}

	/**
     * Get a genre based on a string containing its name.
     * @param datastore The current datastore instance. 
     * @param name The name of the genre as a String.
     * @return A GAE {@link Entity} for the Genre or <code>null</code> if none or error.
     */
	private static Entity getGenreWithName(DatastoreService datastore,
			String name) 
	{
		Entity genre = null;
        try {
                
                Filter hasName =
                                  new FilterPredicate(NAME_PROPERTY,
                                                      FilterOperator.EQUAL,
                                                      name);
                Query query = new Query(ENTITY_KIND);
                query.setFilter(hasName);
                List<Entity> result = datastore.prepare(query).asList(FetchOptions.Builder.withLimit(10));
                if (result!=null && result.size()>0) {
                        genre=result.get(0);
                }
        } catch (Exception e) {
                // TODO log the error
        }
        return genre;
	}

	//
    // GET A GENRE
    //

    /**
     * Get the genre based on a string containing its name.
     * 
     * @param name A {@link String} containing the name (a <code>long</code> number)
     * @return A GAE {@link Entity} for the Genre or <code>null</code> if none or error.
     */
	public static Entity getGenre(String name) 
	{
        Entity genre = null;
        try {
                DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
                Key genreKey = KeyFactory.createKey(ENTITY_KIND, name);
                genre = datastore.get(genreKey);
        } catch (Exception e) {
                // TODO log the error
        }
        return genre;
	}

	//
    // UPDATE A GENRE
    //
    
    /**
     * Update the current description of the Genre.
     * @param name A string with the genre name.
     * @param description The description of the genre as a String.
     * @return true if succeed and false otherwise
     */
	public static boolean updateGenreCommand(String oldGenreName, String newGenreName) 
	{
        Entity genre = null;
        DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
        Transaction txn = datastore.beginTransaction();
        try {
        		genre = getGenreWithName(oldGenreName);
        		genre.setProperty(NAME_PROPERTY, newGenreName);
                datastore = DatastoreServiceFactory.getDatastoreService();
                datastore.put(genre);
                txn.commit();
        } finally {
            if (txn.isActive()) {
                txn.rollback();
            }
        }
        return true;
	}

	 //
    // DELETE A GENRE
    //
    
    /**
     * Delete the genre if not linked to anything else.
     * @param name A string with the genre name.
     * @return True if succeed, false otherwise.
     */
    public static boolean deleteGenreCommand(String name) {
            try {
                    DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
                    datastore.delete(getKey(name));
            } catch (Exception e) {
                    return false;
            }
            return true;
    }
    
    //
    // QUERY GENRES
    //
    
    /**
     * Return the requested number of genres (e.g. 20).  
     * @param limit The number of genres to be returned. 
     * @return A list of GAE {@link Entity entities}. 
     */
    public static List<Entity> getFirstGenres(int limit) {
            
    		DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
            Query query = new Query(ENTITY_KIND);
            List<Entity> result = datastore.prepare(query).asList(FetchOptions.Builder.withLimit(limit));
            return result;
    }
    
    
    /**
     * Assign the parameter results to the local List variable result.  
     * @param results List of entities. 
     * @return nothing. 
     */
    public static void setResults(List<Entity> results)
    {
    	result = results;
    }
    
    /**
     * Return the local List variable result.  
     * @param none. 
     * @return result List variable. 
     */
    public static List<Entity> getResults()
    {
    	return result;
    }

    /**
     * Search for the genres matching the search String parameter value.
     * The query result is send to the local List variable result by 
     * using the setResults(List<Entity) method.
     * @param search A String of the search query (e.g. "Lima", "Darna"). 
     * @return nothing. 
     */
	public static void searchGenreCommand(String search) 
	{

        try {
                
                Filter hasSearch = new FilterPredicate(NAME_PROPERTY,
                                                      FilterOperator.EQUAL,
                                                      search);
                Query query = new Query(ENTITY_KIND);
                query.setFilter(hasSearch);
                DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
				setResults(datastore.prepare(query).asList(FetchOptions.Builder.withLimit(10)));
                
        } catch (Exception e) {
                // TODO log the error
        }
        

	}

	
	public static Entity getGenreByKey(Key key) 
	{
        Entity venue = null;
        try {
                DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
                venue = datastore.get(key);
        } catch (Exception e) {
                // TODO log the error
        }
        return venue;
	}

}